name: Benchmark MyBot against all opponents
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  evilbot:
    uses: ./.github/workflows/benchmark.yaml
    with:
      opponent: EvilBot
      threads: 25

