name: Benchmark MyBot against all opponents
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  evilbot_benchmark:
    uses: ./.github/workflows/benchmark.yaml
    with:
      opponent: EvilBot
      threads: 25

  evilbot_publish:
    uses: ./.github/workflows/publish-result.yaml
    needs: evilbot_benchmark
    if: ${{ github.event_name == 'pull_request' }}
    with:
      opponent: EvilBot
      pull_number: ${{ github.event.pull_request.number }}
      wins: ${{ fromJSON(needs.evilbot_benchmark.outputs.wins) }}
      draws: ${{ fromJSON(needs.evilbot_benchmark.outputs.draws) }}
      losses: ${{ fromJSON(needs.evilbot_benchmark.outputs.losses) }}

  stockfish_0_benchmark:
    uses: ./.github/workflows/benchmark.yaml
    with:
      opponent: Stockfish
      threads: 25
      run: |
        cd Chess-Challenge
        wget https://github.com/official-stockfish/Stockfish/releases/download/sf_16/stockfish-ubuntu-x86-64-avx2.tar
        tar -xf stockfish-ubuntu-x86-64-avx2.tar
        echo "STOCKFISH_BIN=stockfish/stockfish-ubuntu-x86-64-avx2" >> $GITHUB_ENV
        echo "STOCKFISH_LEVEL=0" >> $GITHUB_ENV

  stockfish_0_publish:
    uses: ./.github/workflows/publish-result.yaml
    needs: stockfish_0_benchmark
    if: ${{ github.event_name == 'pull_request' }}
    with:
      opponent: Stockfish (0)
      pull_number: ${{ github.event.pull_request.number }}
      wins: ${{ fromJSON(needs.stockfish_0_benchmark.outputs.wins) }}
      draws: ${{ fromJSON(needs.stockfish_0_benchmark.outputs.draws) }}
      losses: ${{ fromJSON(needs.stockfish_0_benchmark.outputs.losses) }}
