name: Benchmark & Publish

on:
  workflow_call:
    inputs:
      opponent:
        required: true
        type: string
      suffix:
        required: false
        type: string
      threads:
        required: true
        type: number
      run:
        required: false
        type: string

jobs:
  prepare:
    name: pre-pre-Publish
    runs-on: ubuntu-latest
    env:
      OPPONENT: ${{ inputs.opponent }}
      SUFFIX: ${{ inputs.suffix }}
    outputs:
      opponent_long: ${{ steps.prepare.outputs.opponent_long }}
    steps:
    - name: Prepare long name
      id: prepare
      run: |
        OPPONENT_LONG="$OPPONENT"
        if [ -n "$SUFFIX" ]; then
          OPPONENT_LONG="$OPPONENT ($SUFFIX)"
        fi
        echo "opponent_long=$OPPONENT_LONG" >> $GITHUB_OUTPUT

  benchmark:
    uses: ./.github/workflows/benchmark.yaml
    with:
      opponent: ${{ inputs.opponent }}
      suffix: ${{ inputs.suffix }}
      threads: ${{ fromJSON(inputs.threads) }}
      run: ${{ inputs.run }}

  publish:
    uses: ./.github/workflows/publish-result.yaml
    needs:
      - benchmark
      - prepare
    if: ${{ github.event_name == 'pull_request' }}
    with:
      opponent: ${{ needs.prepare.outputs.opponent_long }}
      pull_number: ${{ github.event.pull_request.number }}
      wins: ${{ fromJSON(needs.benchmark.outputs.wins) }}
      draws: ${{ fromJSON(needs.benchmark.outputs.draws) }}
      losses: ${{ fromJSON(needs.benchmark.outputs.losses) }}
