name: Benchmark MyBot against all opponents
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  evilbot_benchmark:
    uses: ./.github/workflows/benchmark.yaml
    with:
      opponent: EvilBot
      threads: 25

  evilbot_publish:
    if: ${{ github.event_name == 'pull_request' }}
    needs: evilbot_benchmark
    uses: ./.github/workflows/publish-result.yaml
    with:
      opponent: EvilBot
      pull_number: ${{ github.event.pull_request.number }}
      wins: ${{ needs.evilbot_benchmark.outputs.wins }}
      draws: ${{ needs.evilbot_benchmark.outputs.draws }}
      losses: ${{ needs.evilbot_benchmark.outputs.losses }}

