name: Publish Results

on:
  workflow_call:
    inputs:
      opponent:
        required: true
        type: string
      pull_number:
        required: true
        type: number
      wins:
        required: true
        type: number
      draws:
        required: true
        type: number
      losses:
        required: true
        type: number

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.export.outputs.short_sha }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Calculate and export context
      id: export
      run: |
        LAST_COMMIT_SHA=${{ github.event.pull_request.head.sha }}
        SHORT_SHA=$(echo $LAST_COMMIT_SHA | cut -c 1-7)
        echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT

  publish_stats:
    needs: prepare
    runs-on: ubuntu-latest

    steps:
    - name: Comment PR
      uses: actions/github-script@v6
      with:
        script: |
          const opponent = '${{ inputs.opponent }}';
          const wins = '${{ inputs.wins }}';
          const draws = '${{ inputs.draws }}';
          const losses = '${{ inputs.losses }}';
          const shortSha = '${{ needs.prepare.outputs.short_sha }}';
          const pull_number = ${{ inputs.pull_number }};

          const pr = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: ${{ inputs.pull_number }}
          });

          const existingDescription = pr.data.body || '';
          let prDescription = existingDescription;
          let benchmarkIndexStart = existingDescription.indexOf('<!-- benchmark start -->');
          let benchmarkIndexEnd = existingDescription.indexOf('<!-- benchmark end -->');
          let benchmarkSection = '';

          const newLine = `| ${opponent} | ${wins} | ${draws} | ${losses} | ${shortSha} |\n`;

          if (benchmarkIndexStart === -1) {
            // Benchmark section does not exist. Add it.
            benchmarkSection = `\n<!-- benchmark start -->\n| Opponent | Wins | Draws | Losses | Commit |\n| --- | --- | --- | --- | --- |\n${newLine}<!-- benchmark end -->\n`;
            prDescription += benchmarkSection;
          } else {
            // Benchmark section exists. Update it.
            benchmarkSection = existingDescription.slice(benchmarkIndexStart + 23, benchmarkIndexEnd);
            let opponentIndex = benchmarkSection.indexOf(`| ${opponent} |`);

            if (opponentIndex === -1) {
              // Opponent row does not exist. Add it.
              benchmarkSection += newLine;
            } else {
              // Opponent row exists. Update it.
              const opponentIndexEnd = benchmarkSection.indexOf('\n', opponentIndex);
              benchmarkSection = benchmarkSection.slice(0, opponentIndex) + newLine + benchmarkSection.slice(opponentIndexEnd+1);
            }

            prDescription = existingDescription.slice(0, benchmarkIndexStart + 23) + benchmarkSection + existingDescription.slice(benchmarkIndexEnd);
          }

          github.rest.pulls.update({
            pull_number: pull_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: prDescription
          });

